.SILENT:

build:
	@echo "Compiling renderer..."
	gcc -Wall -std=gnu99 ./src/*.c -lSDL2 -lm -o renderer

run:
	@echo "Running renderer..."
	./renderer

clean:
	@echo "Cleaning repository..."
	rm renderer
